config/routes.rb
Myapp::Application.routes.draw do
  resources :cities

  resources :states do
    member do
      get :show_cities_details
    end
  end

  resources :countries do
    member do
      get :show_states_details
    end
  end

  root :to => 'countries#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  has_one  :wiki_link, as: :linkable 
  belongs_to :state

  validates_presence_of :name
  validates_presence_of :state_id
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
  has_one  :currency
  has_one  :time_zone
  has_one  :wiki_link, as: :linkable

  validates_presence_of :name

  def area
    area = 0
    self.states.each do|state|
      area += state.area
    end
    return area
  end

  def literacy
    sum = 0
    self.states.each do|state|
      sum += state.literacy
    end
    return (sum/self.states.count)
  end

  def population
    population = 0
    self.states.each do|state|
      population += state.population
    end
    return population
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  belongs_to :country
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  belongs_to :country
  has_one  :wiki_link, as: :linkable 

  validates_presence_of :name
  validates_presence_of :country_id
  
  def area
    self.cities.sum(:area)
  end

  def literacy
    self.cities.average(:literacy)
  end

  def population
    self.cities.sum(:population)
  end
end

app/models/time_zone.rb
class TimeZone < ActiveRecord::Base
  belongs_to :country
end

app/models/wiki_link.rb
class WikiLink < ActiveRecord::Base
  belongs_to :linkable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  layout "layouts/default"
  before_filter :init_manager_and_presenter

  def index
    countries = Country.all
    @columns_headers = @manager.country_datatable_columns

    respond_to do |format|
      format.html {render :index}
      format.json do
        countries_data = @manager.prepare_countries_data(countries)
        countries_data_json = @presenter.format_countries_data(countries_data)
        render :json => @presenter.generate_datatable_json(params, countries_data_json, countries_data.count)
      end
    end
  end

  def show_states_details
    @country = Country.find_by_id(params[:id])
    states = State.where(country_id: @country.id)
    @columns_headers = @manager.state_datatable_columns
    respond_to do |format|
      format.html {render :template => '/countries/show_states'}
      format.json do 
        states_data = @manager.prepare_states_data(states)
        states_data_json = @presenter.format_states_data(states_data)
        render :json => @presenter.generate_datatable_json(params, states_data_json, states_data.count)
      end
    end
  end

  private
    def init_manager_and_presenter
      @manager = Manager.new
      @presenter = Presenter.new
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
layout 'layouts/default'
  before_filter :init_manager_and_presenter

  def show_cities_details
    @state = State.find_by_id(params[:id])
    cities = City.where(state_id: @state.id)
    @columns_headers = @manager.city_datatable_columns
    respond_to do |format|
      format.html {render :template => '/states/show_cities'}
      format.json do 
        cities_data = @manager.prepare_cities_data(cities)
        cities_data_json = @presenter.format_cities_data(cities_data)
        render :json => @presenter.generate_datatable_json(params, cities_data_json, cities_data.count)
      end
    end
  end

  private
  def init_manager_and_presenter
    @manager = Manager.new
    @presenter = Presenter.new
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  layout "layouts/default", :only => [:index]
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/countries/index.html.erb
<h1>Listing countries</h1>

<table id="countries_list" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered" data-url="<%= countries_path%>">
  <thead>
    <tr>
      <%= @presenter.display_column_headers(@columns_headers) %>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

app/views/countries/show_states.html.erb
<h1>Listing States in <%= @country.name%></h1>

<table id="country_states_list" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered" data-url="<%= show_states_details_country_path(@country.id)%>">
  <thead>
    <tr>
      <%= @presenter.display_column_headers(@columns_headers) %>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Myapp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Countries List", countries_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/states/show_cities.html.erb
<h1>Listing Cities in <%= @state.name%></h1>

<table id="state_cities_list" cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered" data-url="<%= show_cities_details_state_path(@state.id)%>">
  <thead>
    <tr>
      <%= @presenter.display_column_headers(@columns_headers) %>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>